routing: local # local | domain
tls: false # only supported with existing traefik

reverseProxy:
    create: true
    network: rp

domain: vindelicum.eu

services:
    api:
        subdomain: omniviv-api
        database:
            type: sqlite
            storage:
                volumeName: api-database
                absolutePath: null
        build:
            enabled: true
            context: ../../api
            dockerfile: Dockerfile
        image: ghcr.io/firstdorsal/omniviv-api:main
    web:
        subdomain: omniviv
        build:
            enabled: true
            context: ../../web
            dockerfile: Dockerfile
        image: ghcr.io/firstdorsal/omniviv-web:main
    martin:
        subdomain: omniviv-martin
        image: ghcr.io/maplibre/martin
        dataPath: ./data/
        cacheSeconds: 86400 # 1 day
